pipelines:
# Individual Builds for Mono Repo
  - name: build_boutique_adsvc
    steps:
    - name: extra_buildInfo
      type: Bash
      configuration:
        inputSteps:
          - name: push_adsvc
        inputResources:
          - name: adsvc_repo
        outputResources:
          - name: ads_propertybag
      execution:
        onExecute:
          - write_output ads_propertybag imageTag=${run_number} commitSha=$res_adsvc_repo_commitSha commiterLogin=$res_adsvc_repo_committerLogin
    - name: build_adsvc
      type: DockerBuild
      configuration:
        affinityGroup: fmkGroup
        dockerFileLocation: adservice
        dockerFileName: Dockerfile
        dockerImageName: ${int_server_name_value}.jfrog.io/boutiquecd-images/ adservice
        dockerImageTag: ${run_number}
        dockerOptions: --build-arg SERVER_NAME=${int_server_name_value}
        integrations:        
          - name: artifactory
          - name: server_name
        inputResources:
          - name: adsvc_repo
    - name: push_adsvc
      type: DockerPush
      configuration:
        affinityGroup: fmkGroup
        targetRepository: boutiquecd-images        
        forceXrayScan:  true             # default false
        failOnScan:  false         # default true
        autoPublishBuildInfo: true       # default false
        integrations:
          - name: artifactory
        inputSteps:
          - name: build_adsvc
        outputResources:
          - name: adsvc_build_info
   
  - name: build_boutique_cartsvc
    steps:
    - name: extra_buildInfo
      type: Bash
      configuration:
        inputSteps:
          - name: push_cartsvc
        inputResources:
          - name: cartsvc_repo
        outputResources:
          - name: cart_propertybag
      execution:
        onExecute:
          - write_output cart_propertybag imageTag=${run_number} commitSha=$res_cartsvc_repo_commitSha commiterLogin=$res_cartsvc_repocommitterLogin
    - name: build_cartsvc
      type: DockerBuild
      configuration:
        affinityGroup: fmkGroup
        dockerFileLocation: cartservice/src
        dockerFileName: Dockerfile
        dockerImageName: ${int_server_name_value}.jfrog.io/boutiquecd-images/cartservice
        dockerImageTag: ${run_number}
        dockerOptions: --build-arg SERVER_NAME=${int_server_name_value}
        integrations:        
          - name: artifactory
          - name: server_name
        inputResources:
          - name: cartsvc_repo
    - name: push_cartsvc
      type: DockerPush
      configuration:
        affinityGroup: fmkGroup
        targetRepository: boutiquecd-images        
        forceXrayScan:  true             # default false
        failOnScan:  false         # default true
        autoPublishBuildInfo: true 
        integrations:
          - name: artifactory
        inputSteps:
          - name: build_cartsvc
        outputResources:
          - name: cartsvc_build_info
  
  - name: build_boutique_checkoutsvc
    steps:
    - name: extra_buildInfo
      type: Bash
      configuration:
        inputSteps:
          - name: push_checkoutsvc
        inputResources:
          - name: checkoutsvc_repo
        outputResources:
          - name: checkout_propertybag
      execution:
        onExecute:
          - write_output checkout_propertybag imageTag=${run_number} commitSha=$res_checkoutsvc_repo_commitSha commiterLogin=$res_checkoutsvc_repo_committerLogin
    - name: build_checkoutsvc
      type: DockerBuild
      configuration:
        affinityGroup: fmkGroup
        dockerFileLocation: checkoutservice
        dockerFileName: Dockerfile
        dockerImageName: ${int_server_name_value}.jfrog.io/boutiquecd-images/checkoutservice
        dockerImageTag: ${run_number}
        dockerOptions: --build-arg SERVER_NAME=${int_server_name_value}
        integrations:        
          - name: artifactory
          - name: server_name
        inputResources:
          - name: checkoutsvc_repo
    - name: push_checkoutsvc
      type: DockerPush
      configuration:
        affinityGroup: fmkGroup
        targetRepository: boutiquecd-images        
        forceXrayScan:  true             # default false
        failOnScan:  false         # default true
        autoPublishBuildInfo: true 
        integrations:
          - name: artifactory
        inputSteps:
          - name: build_checkoutsvc
        outputResources:
          - name: checkoutsvc_build_info

  - name: build_boutique_currencysvc
    steps:
    - name: extra_buildInfo
      type: Bash
      configuration:
        inputSteps:
          - name: push_currencysvc
        inputResources:
          - name: currencysvc_repo
        outputResources:
          - name: currency_propertybag
      execution:
        onExecute:
          - write_output currency_propertybag imageTag=${run_number} commitSha=$res_currencysvc_repo_commitSha commiterLogin=$res_currencysvc_repo_committerLogin
    - name: build_currencysvc
      type: DockerBuild
      configuration:
        affinityGroup: fmkGroup
        dockerFileLocation: currencyservice
        dockerFileName: Dockerfile
        dockerImageName: ${int_server_name_value}.jfrog.io/boutiquecd-images/currencyservice
        dockerImageTag: ${run_number}
        dockerOptions: --build-arg SERVER_NAME=${int_server_name_value}
        integrations:        
          - name: artifactory
          - name: server_name
        inputResources:
          - name: currencysvc_repo
    - name: push_currencysvc
      type: DockerPush
      configuration:
        affinityGroup: fmkGroup
        targetRepository: boutiquecd-images        
        forceXrayScan:  true             # default false
        failOnScan:  false         # default true
        autoPublishBuildInfo: true 
        integrations:
          - name: artifactory
        inputSteps:
          - name: build_currencysvc
        outputResources:
          - name: currencysvc_build_info

  - name: build_boutique_emailsvc
    steps:
    - name: extra_buildInfo
      type: Bash
      configuration:
        inputSteps:
          - name: push_emailsvc
        inputResources:
          - name: emailsvc_repo
        outputResources:
          - name: email_propertybag
      execution:
        onExecute:
          - write_output email_propertybag imageTag=${run_number} commitSha=$res_emailsvc_repo_commitSha commiterLogin=$res_emailsvc_repo_committerLogin
    - name: build_emailsvc
      type: DockerBuild
      configuration:
        affinityGroup: fmkGroup
        dockerFileLocation: emailservice
        dockerFileName: Dockerfile
        dockerImageName: ${int_server_name_value}.jfrog.io/boutiquecd-images/emailservice
        dockerImageTag: ${run_number}
        dockerOptions: --build-arg SERVER_NAME=${int_server_name_value}
        integrations:        
          - name: artifactory
          - name: server_name
        inputResources:
          - name: emailsvc_repo
    - name: push_emailsvc
      type: DockerPush
      configuration:
        affinityGroup: fmkGroup
        targetRepository: boutiquecd-images        
        forceXrayScan:  true             # default false
        failOnScan:  false         # default true
        autoPublishBuildInfo: true 
        integrations:
          - name: artifactory
        inputSteps:
          - name: build_emailsvc
        outputResources:
          - name: emailsvc_build_info

  - name: build_boutique_frontend
    steps:
    - name: extra_buildInfo
      type: Bash
      configuration:
        inputSteps:
          - name: push_frontend
        inputResources:
          - name: frontendsvc_repo
        outputResources:
          - name: frontend_propertybag
      execution:
        onExecute:
          - write_output frontend_propertybag imageTag=${run_number} commitSha=$res_frontendsvc_repo_commitSha commiterLogin=$res_frontendsvc_repo_committerLogin
    - name: build_frontend
      type: DockerBuild
      configuration:
        affinityGroup: fmkGroup
        dockerFileLocation: frontend
        dockerFileName: Dockerfile
        dockerImageName: ${int_server_name_value}.jfrog.io/boutiquecd-images/frontend
        dockerImageTag: ${run_number}
        dockerOptions: --build-arg SERVER_NAME=${int_server_name_value}
        integrations:        
          - name: artifactory
          - name: server_name
        inputResources:
          - name: frontendsvc_repo
    - name: push_frontend
      type: DockerPush
      configuration:
        affinityGroup: fmkGroup
        targetRepository: boutiquecd-images        
        forceXrayScan:  true             # default false
        failOnScan:  false         # default true
        autoPublishBuildInfo: true 
        integrations:
          - name: artifactory
        inputSteps:
          - name: build_frontend
        outputResources:
          - name: frontend_build_info

  - name: build_boutique_paymentsvc
    steps:
    - name: extra_buildInfo
      type: Bash
      configuration:
        inputSteps:
          - name: push_paymentsvc
        inputResources:
          - name: paymentsvc_repo
        outputResources:
          - name: payment_propertybag
      execution:
        onExecute:
          - write_output payment_propertybag imageTag=${run_number} commitSha=$res_paymentsvc_repo_commitSha commiterLogin=$res_paymentsvc_repo_committerLogin
    - name: build_paymentsvc
      type: DockerBuild
      configuration:
        affinityGroup: fmkGroup
        dockerFileLocation: paymentservice
        dockerFileName: Dockerfile
        dockerImageName: ${int_server_name_value}.jfrog.io/boutiquecd-images/paymentservice
        dockerImageTag: ${run_number}
        dockerOptions: --build-arg SERVER_NAME=${int_server_name_value}
        integrations:        
          - name: artifactory
          - name: server_name
        inputResources:
          - name: paymentsvc_repo
    - name: push_paymentsvc
      type: DockerPush
      configuration:
        affinityGroup: fmkGroup
        targetRepository: boutiquecd-images        
        forceXrayScan:  true             # default false
        failOnScan:  false         # default true
        autoPublishBuildInfo: true 
        integrations:
          - name: artifactory
        inputSteps:
          - name: build_paymentsvc
        outputResources:
          - name: paymentsvc_build_info

  - name: build_boutique_productcatalogsvc
    steps:
    - name: extra_buildInfo
      type: Bash
      configuration:
        inputSteps:
          - name: push_productcatalogsvc
        inputResources:
          - name: productcatalogsvc_repo
        outputResources:
          - name: product_propertybag
      execution:
        onExecute:
          - write_output product_propertybag imageTag=${run_number} commitSha=$res_productcatalogsvc_repo_commitSha commiterLogin=$res_productcatalogsvc_repo_committerLogin
    - name: build_productcatalogsvc
      type: DockerBuild
      configuration:
        affinityGroup: fmkGroup
        dockerFileLocation: productcatalogservice
        dockerFileName: Dockerfile
        dockerImageName: ${int_server_name_value}.jfrog.io/boutiquecd-images/productcatalogservice
        dockerImageTag: ${run_number}
        dockerOptions: --build-arg SERVER_NAME=${int_server_name_value}
        integrations:        
          - name: artifactory
          - name: server_name
        inputResources:
          - name: productcatalogsvc_repo
    - name: push_productcatalogsvc
      type: DockerPush
      configuration:
        affinityGroup: fmkGroup
        targetRepository: boutiquecd-images       
        forceXrayScan:  true             # default false
        failOnScan:  false         # default true
        autoPublishBuildInfo: true 
        integrations:
          - name: artifactory
        inputSteps:
          - name: build_productcatalogsvc
        outputResources:
          - name: productcatalogsvc_build_info

  - name: build_boutique_recommendationsvc
    steps:
    - name: extra_buildInfo
      type: Bash
      configuration:
        inputSteps:
          - name: push_recommendationsvc
        inputResources:
          - name: recommendationsvc_repo
        outputResources:
          - name: recommendations_propertybag
      execution:
        onExecute:
          - write_output recommendations_propertybag imageTag=${run_number} commitSha=$res_recommendationsvc_repo_commitSha commiterLogin=$res_recommendationsvc_repo_committerLogin
    - name: build_recommendationsvc
      type: DockerBuild
      configuration:
        affinityGroup: fmkGroup
        dockerFileLocation: recommendationservice
        dockerFileName: Dockerfile
        dockerImageName: ${int_server_name_value}.jfrog.io/boutiquecd-images/recommendationservice
        dockerImageTag: ${run_number}
        dockerOptions: --build-arg SERVER_NAME=${int_server_name_value}
        integrations:        
          - name: artifactory
          - name: server_name
        inputResources:
          - name: recommendationsvc_repo
    - name: push_recommendationsvc
      type: DockerPush
      configuration:
        affinityGroup: fmkGroup
        targetRepository: boutiquecd-images        
        forceXrayScan:  true             # default false
        failOnScan:  false         # default true
        autoPublishBuildInfo: true 
        integrations:
          - name: artifactory
        inputSteps:
          - name: build_recommendationsvc
        outputResources:
          - name: recommendationsvc_build_info

  - name: build_boutique_shippingsvc
    steps:
    - name: extra_buildInfo
      type: Bash
      configuration:
        inputSteps:
          - name: push_shippingsvc
        inputResources:
          - name: shippingsvc_repo
        outputResources:
          - name: shipping_propertybag
      execution:
        onExecute:
          - write_output shipping_propertybag imageTag=${run_number} commitSha=$res_shippingsvc_repo_commitSha commiterLogin=$res_shippingsvc_repo_committerLogin
    - name: build_shippingsvc
      type: DockerBuild
      configuration:
        affinityGroup: fmkGroup
        dockerFileLocation: shippingservice
        dockerFileName: Dockerfile
        dockerImageName: ${int_server_name_value}.jfrog.io/boutiquecd-images/shippingservice
        dockerImageTag: ${run_number}
        dockerOptions: --build-arg SERVER_NAME=${int_server_name_value}
        integrations:        
          - name: artifactory
          - name: server_name
        inputResources:
          - name: shippingsvc_repo
    - name: push_shippingsvc
      type: DockerPush
      configuration:
        affinityGroup: fmkGroup
        targetRepository: boutiquecd-images        
        forceXrayScan:  true             # default false
        failOnScan:  false         # default true
        autoPublishBuildInfo: true 
        integrations:
          - name: artifactory
        inputSteps:
          - name: build_shippingsvc
        outputResources:
          - name: shippingsvc_build_info

  - name: build_boutique_loadgen
    steps:
    - name: extra_buildInfo
      type: Bash
      configuration:
        inputSteps:
          - name: push_loadgen
        inputResources:
          - name: loadgensvc_repo
        outputResources:
          - name: load_propertybag
      execution:
        onExecute:
          - write_output load_propertybag imageTag=${run_number} commitSha=$res_loadgensvc_repo_commitSha commiterLogin=$res_loadgensvc_repo_committerLogin
    - name: build_loadgen
      type: DockerBuild
      configuration:
        affinityGroup: fmkGroup
        dockerFileLocation: loadgenerator
        dockerFileName: Dockerfile
        dockerImageName: ${int_server_name_value}.jfrog.io/boutiquecd-images/loadgenerator
        dockerImageTag: ${run_number}
        dockerOptions: --build-arg SERVER_NAME=${int_server_name_value}
        integrations:        
          - name: artifactory
          - name: server_name
        inputResources:
          - name: loadgensvc_repo
    - name: push_loadgen
      type: DockerPush
      configuration:
        affinityGroup: fmkGroup
        targetRepository: boutiquecd-images
        forceXrayScan:  true             # default false
        failOnScan:  false         # default true
        autoPublishBuildInfo: true 
        integrations:
          - name: artifactory
        inputSteps:
          - name: build_loadgen
        outputResources:
          - name: loadgenerator_build_info


