resources:
  - name: ApplicationRepo
    type: GitRepo
    configuration:
      gitProvider: Github
      path: gdg-cloud-montreal/online-boutique
  - name: docker_frontend_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactory
      buildName: build_and_deploy_cloudrun_pipeline
      buildNumber: ${run_number}

pipelines:
  - name: build_and_deploy_cloudrun_pipeline
    steps:
    - name: build_frontend_docker
      type: DockerBuild
      configuration:
        affinityGroup: fmkGroup
        dockerFileLocation: src/frontend
        dockerFileName: Dockerfile
        dockerImageName: ${int_server_name_value}.jfrog.io/boutique/frontend
        dockerImageTag: ${run_number}
        dockerOptions: --build-arg SERVER_NAME=${int_server_name_value}
        integrations:        
          - name: artifactory
          - name: server_name
        inputResources:
          - name: source_code
    - name: push_frontend_docker
      type: DockerPush
      configuration:
        affinityGroup: fmkGroup
        targetRepository: docker-local
        autoPublishBuildInfo: true
        integrations:
          - name: artifactory
        inputSteps:
          - name: build_frontend_docker
        outputResources:
          - name: docker_frontend_build_info
    - name: xray_scan_frontend_docker
      type: XrayScan
      configuration:
        affinityGroup: fmkGroup
        failOnScan: false
        inputSteps:
          - name: push_frontend_docker
        inputResources:
          - name: docker_frontend_build_info
            trigger: false
