resources:
  - name: ApplicationRepo
    type: GitRepo
    configuration:
      gitProvider: Container_Build
      path: gdg-cloud-montreal/online-boutique
  - name: frontend_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactory
      buildName: build_boutique
      buildNumber: ${run_number}

pipelines:
  - name: build_boutique_frontend
    steps:
    - name: build_frontend
      type: DockerBuild
      configuration:
        affinityGroup: fmkGroup
        dockerFileLocation: frontend
        dockerFileName: Dockerfile
        dockerImageName: ${int_server_name_value}.jfrog.io/boutique/frontend
        dockerImageTag: ${run_number}
        dockerOptions: --build-arg SERVER_NAME=${int_server_name_value}
        integrations:        
          - name: Artifactory_intergration
          - name: server_name
        inputResources:
          - name: source_code
    - name: push_frontend_docker
      type: DockerPush
      configuration:
        affinityGroup: fmkGroup
        targetRepository: boutique
        autoPublishBuildInfo: true
        integrations:
          - name: Artifactory_intergration
        inputSteps:
          - name: build_frontend
        outputResources:
          - name: frontend_build_info
    - name: xray_scan_frontend_docker
      type: XrayScan
      configuration:
        affinityGroup: fmkGroup
        failOnScan: false
        inputSteps:
          - name: frontend_docker
        inputResources:
          - name: frontend_build_info
            trigger: false
